### ISSUE TITLE
Issue in clusters calculation depending on the location

### ISSUE THREAD

**Issue by cuentasbesmartmobile** [sharewire/google-maps-clustering#13]
Hi !

I'm from Argentina and saw that with negatives values for latitude and longitude the method getClusters return 0. 

I fixed it replacing in ClusterManager.java Line: 176 the next sentence: 

             `   List<T> points = mQuadTree.queryRange(north > south ? north : south, west < east ? west : east, south < north ? south : north, east > west ? east : west);`

I not have much time now to test whether is the ideal and global solution for the whole map, but it can be a good starting point.

Regards!

**Comment by makovkastar** [comment]
Hi, thanks for your report, I will check it soon.

**Comment by makovkastar** [comment]
@cuentasbesmartmobile it would be nice if you provided a few locations that cause the problem.
