### ISSUE TITLE
No way to programatically display infoWindow for ClusterItem

### ISSUE THREAD

**Issue by PJHaynes304** [sharewire/google-maps-clustering#20]
Can't find a way to get hold of the ClusterItem to then be able to programatically show infoWindow. Is there a way to do this that I've missed? If not I'll work on a  pull request as I think it would be really useful.

Thanks

**Comment by fish-4-fun** [comment]
From what I see, you can still use map.setOnMarkerClickListener, but this will not allow you to take advantage of the ClusterManager.Callbacks which gives you access to your "object" or cluster item type...kind of defeats the point.

**Comment by PJHaynes304** [comment]
Yes indeed. The built in map markers hold only a title, snippet and location. I need all my other data for each marker. 

I've done a workaround for now and with Google's new pricing policy for the 'Google Maps Platform' https://cloud.google.com/maps-platform/user-guide/pricing-changes/
I'm very reluctant to commit any more time than necessary on this as I may end up changing maps at some point down the line!
