### ISSUE TITLE
OutOfMemoryError createBitmap

### ISSUE THREAD

**Issue by Gawvie** [sharewire/google-maps-clustering#3]
Hi Alex Melnykov, 
Firstly I really thank you for your library. I solved my problems about rendering more than 100k markers. But now I'm facing out of memory error about bitmap when I leave and came back to map fragment. I think bitmap resources may not be cleared when fragment was destroyed at first time. Because the first time the map and its clustering is working fine. Do you have any suggestion to solve this problem? I'm new for map implementing, feel free to advise me.
Thanks,
Gaw

**Comment by makovkastar** [comment]
Hello, Gawvie. Are you using a standard cluster renderer implementation or a custom one?

**Comment by Gawvie** [comment]
I used a standard one but I seperated setItems to every 5000 locations. But
I've checked this modification didn't be cause of OutOfMemoryError.

Thanks for your reply :)
Gaw


www.appsynth.net
+66 (0)2 168 3297
Kritsana Yamphean (Gaw)
Android Developer
kaw@appsynth.net
086 9853240

Asia's Leading Mobile Agency

**Comment by makovkastar** [comment]
Can you please post the code of your setup? And what size is the icon you use for cluster items?

**Comment by makovkastar** [comment]
I assume the issue has been solved, so I'm closing it.
