### ISSUE TITLE
[Question] Set custom marker icon?

### ISSUE THREAD

**Issue by carlosmacmar** [sharewire/google-maps-clustering#4]
Hi, first of all, thank you for you contribution. I tried the original library by Google and, yes, it's slow. So I found yours! But I'm having some trouble making things work.
I have a custom marker, made like this:

```
@Override
public void onMapReady(GoogleMap map) {
      final IconGenerator iconFactory = new IconGenerator(this);
           iconFactory.setStyle(IconGenerator.STYLE_BLUE);
    
    addIcon(iconFactory, "9872", locationExample); 
}
private void addIcon(IconGenerator iconFactory, CharSequence text, LatLng position) {
        MarkerOptions markerOptions = new MarkerOptions().
                icon(BitmapDescriptorFactory.fromBitmap(iconFactory.makeIcon(text))).
                position(position).
                anchor(iconFactory.getAnchorU(), iconFactory.getAnchorV());

        map.addMarker(markerOptions);
```

And now I'm trying to add your cluster library to it, but I dont know if I can use my already customized markers. If not, does your library have a custom marker icon option? I've tried to do it, but I can't get it work. Could you please give me an example of a custom marker? I just need a marker with a number inside.

This was my best try:
```
final ClusterManager<SampleClusterItem> clusterManager = new ClusterManager<>(this, map);
        clusterManager.setCallbacks(new ClusterManager.Callbacks<SampleClusterItem>() {
            @Override
            public boolean onClusterClick(@NonNull Cluster<SampleClusterItem> cluster) {
                Log.d(TAG, "onClusterClick");
                return false;
            }

            @Override
            public boolean onClusterItemClick(@NonNull SampleClusterItem clusterItem) {
                Log.d(TAG, "onClusterItemClick");
                return false;
            }
        });
        map.setOnCameraIdleListener(clusterManager);

        IconStyle.Builder stilo = new IconStyle.Builder(this);
        stilo.setClusterBackgroundColor(Color.BLUE);
        stilo.setClusterTextColor(Color.WHITE);

        DefaultIconGenerator icono = new DefaultIconGenerator(this);
        icono.setIconStyle(stilo.build());
```

Thank you so much :)

**Comment by makovkastar** [comment]
Hello @carlosmacmar. To customize the marker icons create a class and make it implement [IconGenerator](https://github.com/sharewire/google-maps-clustering/blob/master/library/src/main/java/net/sharewire/googlemapsclustering/IconGenerator.java). Then set it using ClusterManager.setIconGenerator(...). Keep in mind that you will have to implement caching of the icons yourself. You can see how it's done in [DefaultIconGenerator](https://github.com/sharewire/google-maps-clustering/blob/master/library/src/main/java/net/sharewire/googlemapsclustering/DefaultIconGenerator.java). Let me know if you need further assistance.

**Comment by Therefore** [comment]
@makovkastar Absolutely loving this library, but can't get IconGenerator to work. I cloned the sample app and made a new class called IconGenerator and implemented IconGenerator here:
```
public class IconGenerator implements net.sharewire.googlemapsclustering.IconGenerator {
    @NonNull
    @Override
    public BitmapDescriptor getClusterIcon(@NonNull Cluster cluster) {
        return null;
    }
    @NonNull
    @Override
    public BitmapDescriptor getClusterItemIcon(@NonNull ClusterItem clusterItem) {
        BitmapDescriptor bitmapDescriptor = BitmapDescriptorFactory.fromResource(R.drawable.r1_1);
        return null;
    }
}
```
The r1_1 is a png in my drawables folder.

in the MapsActivity I tried clusterMarker.setIconGenerator(...);
I'm not sure what to put in the (...).
bonus questions: Can I make the markers .flat(true) and give them a .Rotation(Float)?

Thanks so much for the help

**Comment by makovkastar** [comment]
Hi @Therefore, thanks for your question. From your code I can see that you return `null` from the `getClusterItemIcon` method. After you fix this, you need to set your new icon generator using `clusterManager.setIconGenerator(new IconGenerator())`.

**Comment by Therefore** [comment]
@makovkastar I got this working by modifying the DefaultIconGenerator. Thanks for the help. I have another question about important the library as a module so I'll start a new issue if that's alright.

**Comment by makovkastar** [comment]
OK, good, closing the issue.

**Comment by PJHaynes304** [comment]
After implementing my own CustomIcongenerator and setting it using ClusterManager.setIconGenerator(...) I get a null pointer exception in ClusterRenderer, presumably because the constructor takes a DefaultIconGenerator rather than my CustomIconGenerator? 
java.lang.NullPointerException
  at net.sharewire.googlemapsclustering.Preconditions.checkNotNull(Preconditions.java:9)
  at net.sharewire.googlemapsclustering.ClusterRenderer.getMarkerIcon(ClusterRenderer.java:158)
  at net.sharewire.googlemapsclustering.ClusterRenderer.render(ClusterRenderer.java:116)
  at net.sharewire.googlemapsclustering.ClusterManager$ClusterTask.onPostExecute
(ClusterManager.java:247)
  at net.sharewire.googlemapsclustering.ClusterManager$ClusterTask.onPostExecute
(ClusterManager.java:230)


Is there a way to solve this? Or does it look like I have misunderstood the exception?

**Comment by bonjourrohit89** [comment]
Hi , I am also using this library but I am facing one problem when I am implementing custom marker by using Icon Generator. Below is the code :


        clusterManager.setIconGenerator(new IconGenerator<SimpleClusterModel>() {
            @NonNull
            @Override
            public BitmapDescriptor getClusterIcon(@NonNull net.sharewire.googlemapsclustering.Cluster<SimpleClusterModel> cluster) {


                BitmapDescriptor icon = BitmapDescriptorFactory.fromResource(R.mipmap.beenhere);
                return icon;
            }

            @NonNull
            @Override
            public BitmapDescriptor getClusterItemIcon(@NonNull SimpleClusterModel clusterItem) {
                BitmapDescriptor icon = BitmapDescriptorFactory.fromResource(R.mipmap.pin_pink);
                return icon;
            }
        });

Now my question is How can I set number inside my custom marker icon? or  how can I get the number inside getClusterIcon() to show on custom marker.

**Comment by PJHaynes304** [comment]
@bonjourrohit89 As @makovkastar mentioned above all the magic happens in DefaultIconGenerator. To achieve what you are asking I created my own custom IconGenerator which, just like DefaultIconGenerator, extends ClusterItem and Implements IconGenerator. You can then use the code from DefaultIconGenerator inside your class to set the label on the ClusterIcons and obviously set whatever custom icon you want. 

I did it this way because I wanted the library to remain a drop in grade dependency, you could obviously clone and fork it to make the code editable therefore negating the need to create your own generator.

Hope this helps.

**Comment by bonjourrohit89** [comment]
Thanks @makovkastar  It worked for me. 
One more question I want to know, how can I get selected marker (cluster item) instance. Can you please tell?

Thanks in Advance

**Comment by PJHaynes304** [comment]
@bonjourrohit89 I just create a local variable named clickedMarker and assign it in onClusterItemClick().

**Comment by bonjourrohit89** [comment]
hi @makovkastar Can you please explain in brief?

**Comment by PJHaynes304** [comment]
Inside the onClusterItemClick method you have access to the clusterItem that's been clicked. If you need an instance of it outside of this method then create a variable and assign it inside this method. 

@Override
            public boolean onClusterItemClick(@NonNull ClusterItem clusterItem) {
                clickedMarker = clusterItem;
                return false;
            }

**Comment by bonjourrohit89** [comment]
No, @makovkastar I want to get marker instance when we click of cluster item, How can I get marker instance on cluster item click?

**Comment by PJHaynes304** [comment]
I'm not sure why you would want to do this but you can use the normal onMarkerClickListener.

 mMap.setOnMarkerClickListener(new GoogleMap.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(Marker marker) {
                return false;
            }
        });

**Comment by bonjourrohit89** [comment]
Hi @makovkastar , I have implemented customer marker and it showing fine but sometime my app is to be get crashed It says out of memory error becasue of those custom marker icons. Can you please tell me How can I resolve same?

**Comment by alhudaghifari** [comment]
Hi, how to add different icon in marker ? Can we do that in your library?
Thanks for the explanation.

**Comment by PJHaynes304** [comment]
@alhudaghifari read the previous comments! It’s explained multiple times in this issue.
