### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by zeeshanalibasbasah** [sharewire/google-maps-clustering#5]
I am facing issue with clustering, please see the picture of map its a max zoom of map but still cluster not opened yet?

![screenshot_20180118-144031 1](https://user-images.githubusercontent.com/21197187/35091143-968f50be-fc5d-11e7-9c6f-ce0bb34e6ccb.png)

**Comment by hoordev** [comment]
I has same problem and I not found to solutuon how to expand the group item manual touch or programatically.

**Comment by makovkastar** [comment]
It might be that the items are very close to each other, so they cannot be unclustered even on the max zoom level. Could you check the coordinates of these three items?

**Comment by zeeshanalibasbasah** [comment]
makOvkastar i know they are very close to each other but in google Cluster manager they just unclustered i test it.

**Comment by Therefore** [comment]
@zeeshanalibasbasah Are you sure that you're not doubling or tripling your arraylist of items? I had a similar problem when my onMapReady was called it would generate the objects again. Since the items were in the exact same spot they could not be unclustered.

**Comment by zeeshanalibasbasah** [comment]
the question is whether the multiple items on the same spot but they have to unclustered when map goes to maximum zoom level.

**Comment by makovkastar** [comment]
This library doesn't guarantee that items will be unclustered at the maximum zoom level. It depends on how close they are. Basically, we check if the items fit inside the same rectangle (which is very small at high zoom level) to put them into the same cluster.

We had a similar problem with multiple items inside a cluster on the max zoom level and solved it by showing a list of items when a user clicks on such a cluster.

**Comment by zeeshanalibasbasah** [comment]
please solve this issue when user reached the max zoom level then all item will be unclustered.

**Comment by makovkastar** [comment]
To be honest I don't think it's an issue. I could try playing with the cell size, but other people might have markers so close that they will fall into the same cluster on the max zoom level.

**Comment by zeeshanalibasbasah** [comment]
@makovkastar its up to you whether you solve it or not but its an issue and its the case that you didn't handled.Thanks
