### ISSUE TITLE
synchronization of mQuadTree

### ISSUE THREAD

**Issue by meierjan** [sharewire/google-maps-clustering#8]
Do I understand your code correctly the synchronization of `mQuadTree` is based on the fact that `mExecutor` is single-threaded?

Opening issues is the only option I can think of to ask questions so I hope u don't bother.

**Comment by makovkastar** [comment]
What synchronization do you mean? `mQuadTree` is not synhronized.

**Comment by meierjan** [comment]
What I mean is that `mQuadTree` is accessed from multiple threads/tasks but it's not synhronized to prevent race-conditions. 

I thought that maybe you didn't do that because both threads that access it directly are scheduled on the single-threaded executor and therefore don't need synchronization.

**Comment by makovkastar** [comment]
You are right, `mQuadTree` is only accessed from a single-threaded executor so there shouldn't be any race conditions.
